name: "Node cache"
description: "Setup a NodeJS environment and restore cache if any, given a node version"

inputs:
  node-version:
    description: "Node version to use"
    required: true
    default: lts/*

outputs:
  cache-hit:
    description: "Forward actions/cache cache-hit output"
    value: ${{ steps.node-cache.outputs.cache-hit }}

runs:
  using: "composite"
  steps:
    - name: Node ${{ inputs.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.node-version }}

    - name: Cache node modules
      id: node-cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.npm
          ./node_modules
          ~/.cache/Cypress
        key: ${{ runner.os }}-node-modules-v1-${{ inputs.node-version }}-${{ hashFiles('./package-lock.json') }}
        restore-keys: ${{ runner.os }}-node-modules-v1-${{ inputs.node-version }}-
